### ISSUE TITLE
Figure out Pros and Cons for NoSQL

### ISSUE THREAD

**Issue by elisehellwig** [ucdavisdatalab/workshop_intro_to_databases#3]
Carl has a lot of pros and cons for NoSQL that I am not sure if I understand and/or agree with.

**Comment by cstahmer** [comment]
We can talk about it tomorrow.  All of them boil down to one simple division.  SQL sucks at trees, and NoSQL is good at them.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Elise Hellwig ***@***.***>
Sent: Monday, January 29, 2024 5:08:23 PM
To: ucdavisdatalab/workshop_intro_to_databases ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ucdavisdatalab/workshop_intro_to_databases] Figure out Pros and Cons for NoSQL (Issue #3)


Carl has a lot of pros and cons for NoSQL that I am not sure if I understand and/or agree with.
